# Generated by Django 5.1 on 2024-10-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_categoria_post_contenido_post_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='aprobado',
            field=models.BooleanField(default=True),
        ),
    ]
