# Generated by Django 5.1 on 2024-10-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_etiqueta'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, related_name='posts', to='myblog.etiqueta'),
        ),
    ]
